### ISSUE TITLE
panicking when reading dng file

### ISSUE THREAD

**Issue by hanatos** [dnglab/dnglab#354]
i tried the following on current main branch (93e426304056442fe7c6f7d649307bd5dacebb4e):

```
wget https://discuss.pixls.us/uploads/short-url/5omBHhwSqrjN4GX7LPVgwbpA486.dng
```
and then ran the conversion like:
```
$ RUST_BACKTRACE=1 ./target/release/dnglab convert /tmp/BMPCC\ BRICK\ BUILDING.dng /tmp/dreggn.dng
thread 'dnglab-tokio-worker' panicked at 'called `Result::unwrap()` on an `Err` value: "ljpeg: trying to decode 1952x556 into 976x1112"', rawler/src/decoders/dng.rs:305:85
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1651:5
   3: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
   4: rayon::iter::plumbing::bridge_producer_consumer::helper
   5: rawler::decoders::decode_threaded_multiline
   6: rawler::decoders::dng::DngDecoder::decode_compressed
   7: <rawler::decoders::dng::DngDecoder as rawler::decoders::Decoder>::raw_image
   8: rawler::dng::convert::internal_convert
   9: rawler::dng::convert::convert_raw_file
  10: dnglab::jobs::raw2dng::Raw2DngJob::internal_exec
  11: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  12: tokio::runtime::task::core::CoreStage<T>::poll
  13: tokio::runtime::task::harness::Harness<T,S>::poll
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Converted 0/1 files, 1 failed:
   /tmp/BMPCC BRICK BUILDING.dng
Total time: 0.14s
```

not sure what to make of it, the error message sounds like there is another case of width and height swapped when multiplying by two or so? seems the buffer allocation has ht*2 but would need wd*2.

**Comment by cytrinox** [comment]
Thanks for the bug report, this issue is fixed in #362
